name: ContinuosIntegration

on:
    pull_request:
        branches: [master]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        if: contains(github.event.pull_request.labels.*.name, 'feature/**')

        steps:
            - name: checkout code
              uses: actions/checkout@v3
          
            - name: Build
              uses: docker/build@v1.1.0