name: ContinuosIntegration

on:
    push:
        branches:
            - master

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v3
          
            - name: Build and Push Image to Dockerhub
              uses: docker/build-push-action@v1.1.0
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
                repository: ${{ secrets.DOCKER_USERNAME }}/gitopsfc
                tags: ${{ github.sha }}, latest