name: ContinuosIntegration

on:
    pull_request:
        branches:
            - master
            - develop
            - feature*
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        if: startsWith( github.event.pull_request.head.ref , 'feature/' )

        steps:
            - name: Show branch name
              run: echo ${{ github.event.pull_request.head.ref }}

            - name: checkout code
              uses: actions/checkout@v3
          
            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                go-version: 1.20
            # You can test your matrix by printing the current Go version
            - name: Display Go version
              run: go version

            - name: Build
              run: go build -v ./...