name: ContinuosIntegration

on:
    pull_request:
        branches:
            - master
            - develop

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        if: contains(github.event.pull_request.labels.*.name, 'feature/***')

        steps:
            - name: checkout code
              uses: actions/checkout@v3
          
            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                go-version: 1.20
            # You can test your matrix by printing the current Go version
            - name: Display Go version
              run: go version

            - name: Build
              run: go build -v ./...