name: Feature Branch Pull Request

on:
  pull_request:
    branches:
      - 'feature*'

jobs:
  feature-branch-pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Show branch name
      run: echo ${{ github.event.pull_request.head.ref }}